export const TABLE_RESIZE = 'TABLE_RESIZE'
export const TOOL_FORMATS = 'TOOL_FORMATS'
export const TOOL_COLOR = 'TOOL_COLOR'
export const TOOL_ALIGN = 'TOOL_ALIGN'
export const TOOL_FONT = 'TOOL_FONT'
export const CHANGE_TEXT = 'CHANGE_TEXT'